### PR TITLE
Update to nymea 1.9.5

### PR DESCRIPTION
**Pull request by t-mon**

### CODE REVIEW

**Review by mhei — CHANGES_REQUESTED** [review]
Seems that commit message includes the wrong version.

**Review by martinlukas84 — APPROVED** [review]

**Review by mhei — APPROVED** [review]

**Comment by mhei** [comment]
Sidenote: a link to some kind of changelog would be good to include here in the commit description.

**Comment by t-mon** [comment]
> Sidenote: a link to some kind of changelog would be good to include here in the commit description.

You are right, we changed the way how we announce the changelogs, the old way is offline, the new way is not finished yet. But I will include it once the proper way has been set up.

**Comment by mhei** [comment]
Thanks for the feedback, my comment was not specific to this PR and we should go ahead here. But happy to hear, that this is already WIP.

**Pull request merged**
